import type { NextPage } from 'next'
import Head from 'next/head'
import { SiJava, SiJavascript, SiKotlin, SiTypescript } from 'react-icons/si'
import { FaGithub, FaInstagram, FaLinkedin } from 'react-icons/fa'
import { BsCalendarDateFill, BsFillCalendarFill } from 'react-icons/bs'
import { BiWorld } from 'react-icons/bi'
import { IoSchool } from 'react-icons/io5'


const Home: NextPage = () => {
  return (
    <div className='bg-background-gradient font-reluko'>
      <Head>
        <title>Profile | Arthur</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="preconnect" href="https://fonts.googleapis.com"/> 
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin=''/> 
        <link href="https://fonts.googleapis.com/css2?family=Ruluko&family=Sintony:wght@400;700&display=swap" rel="stylesheet"/>
      </Head>

      <main className='w-screen h-full' style={{minHeight:"calc(100vh - 100px)"}}>
        <div className='h-20 w-full bg-purple relative flex items-center justify-center'>
          <nav className='container flex flex-col md:flex-row items-baseline gap-2 px-3 md:px-0'>
            <h1 className='text-transparent bg-text-gradient bg-clip-text font-bold text-2xl font-sintony'>
              Arthur de Oliveira
            </h1>
            <div className='text-zinc-300 flex text-sm gap-1 font-reluko' style={{}}>
              <h4>Java |</h4>
              <h4>React |</h4>
              <h4>Spring |</h4>
              <h4>Kotlin |</h4>
              <h4>Typescript</h4>
            </div>
          </nav>
        </div>
        <div className='h-full w-full flex justify-center py-8'>
          <section className='container px-8 lg:px-32'>
            <div className='grid lg:grid-cols-3'>

              <div className='flex flex-col items-center lg:items-start'>
                <img src="img/photo.png" alt="Arthur de Oliveira" className=' lg:w-96 flex'/>
                <div className='text-white flex flex-col gap-2 px-8'>
                  <h4 className='flex gap-2 items-center'><BsCalendarDateFill/> 22 years old</h4>
                  <h4 className='flex gap-2 items-center'><BiWorld/> Brazilian</h4>
                  <h4 className='flex gap-2 items-center'><IoSchool/> Computer science | fullstack</h4>
                </div>
              </div>

              <div className='lg:col-span-2 pt-12'>
                <div className='flex flex-col gap-10'>
                  <div className='flex flex-col gap-5'>
                    <h1 className='text-xl text-white font-sintony'>Olá 👋</h1>
                    <h1 className='text-3xl font-bold text-white block'>
                      I`m <span className='text-transparent bg-text-gradient bg-clip-text font-sintony'>Arthur de Oliveira</span>
                    </h1>
                    <p className='text-white text-justify'>
                      Atualmente sou aluno do 8° período de Ciência da computação da UFERSA e possuo formação Técnica em Tecnologia da informação pelo IMD - UFRN. De 2018 à 2020 fui bolsista de projeto de pesquisa, do qual trabalhei com desenvolvimento de sistemas inteligentes. Atualmente sou desenvolvedor pleno e atuo como full stack.
                    </p>
                  </div>
                  <div className='flex gap-5'>
                    <button className='bg-green-600 p-2 px-4 text-white rounded shadow-md'>Contact me</button>
                    <button className='bg-purple-light p-2 px-4 text-white rounded shadow-md'>Download CV</button>
                  </div>

                  <div>
                    <h2 className='text-white'>Languages</h2>
                    <div className='flex gap-3 py-4'>
                      <SiJavascript className='text-yellow-500 text-4xl'/>
                      <SiTypescript className='text-blue-500 text-4xl'/>
                      <SiJava className='text-red-500 text-4xl'/>
                      <SiKotlin className='text-purple-light text-4xl'/>
                    </div>
                  </div>

                  <div>
                    <h2 className='text-white'>Experiencies</h2>
                    <div className='flex flex-col gap-3 py-3'>

                      <div className='w-full h-24 bg-white/5 rounded-lg flex items-center px-6 gap-5'>
                        <span className='text-white text-sm'>2022</span>
                        <img src="img/cloud.png" alt="" />
                        <div>
                          <span className='text-white'>Cloudhumans</span>
                          <p className='text-white text-sm'>Pleno - Fullstack kotlin/java (Spring/React/Vue)</p>
                        </div>
                      </div>

                      <div className='w-full h-24 bg-white/5 rounded-lg flex items-center px-6 gap-5'>
                        <span className='text-white text-sm'>2020</span>
                        <img src="img/solarz.png" alt="" />
                        <div>
                          <span className='text-white'>Solarz</span>
                          <p className='text-white text-sm'>Júnior - Fullstack Java (Spring/Nextjs)</p>
                        </div>
                      </div>

                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </main>
      
      <footer className='bg-violet-800/10 h-[100px] flex justify-center items-center'>
        <div className='container relative flex flex-col items-center gap-2 md:block'>
          <span className='text-zinc-200 text-sm'>Design and Developement by Arthur de Oliveira</span>
          <div className='md:absolute md:top-0 md:left-1/2 md:-translate-x-1/2 text-white text-2xl flex items-center gap-2'>
            <FaGithub/>
            <FaLinkedin/>
            <FaInstagram/>
          </div>
        </div>
      </footer>

    </div>
  )
}

export default Home
